// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTTN_Travel.Models;

namespace TTTN_Travel.Migrations
{
    [DbContext(typeof(TourReContext))]
    [Migration("20210330100809_makePostTabale")]
    partial class makePostTabale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TTTN_Travel.Models.Admin", b =>
                {
                    b.Property<int>("Idad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDAD")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnName("IMAGE")
                        .HasMaxLength(50);

                    b.Property<string>("Passwork")
                        .HasColumnName("PASSWORK")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasColumnName("USERNAME")
                        .HasMaxLength(50);

                    b.HasKey("Idad");

                    b.ToTable("ADMIN");
                });

            modelBuilder.Entity("TTTN_Travel.Models.Dattour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnName("DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("Dc")
                        .IsRequired()
                        .HasColumnName("DC")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasMaxLength(50);

                    b.Property<string>("Ghichu")
                        .HasColumnName("GHICHU")
                        .HasMaxLength(50);

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnName("HOTEN")
                        .HasMaxLength(50);

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnName("SDT")
                        .HasMaxLength(15);

                    b.Property<int>("Songuoi")
                        .HasColumnName("SONGUOI");

                    b.Property<string>("Tentuor")
                        .IsRequired()
                        .HasColumnName("TENTUOR")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DATTOUR");
                });

            modelBuilder.Entity("TTTN_Travel.Models.Kh", b =>
                {
                    b.Property<int>("Idkh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDKH")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dc")
                        .HasColumnName("DC")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasMaxLength(50);

                    b.Property<string>("Hoten")
                        .HasColumnName("HOTEN")
                        .HasMaxLength(50);

                    b.Property<string>("Sdt")
                        .HasColumnName("SDT")
                        .HasMaxLength(15);

                    b.HasKey("Idkh");

                    b.ToTable("KH");
                });

            modelBuilder.Entity("TTTN_Travel.Models.Tintuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anhtintuc");

                    b.Property<string>("Chitiet");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Tentintuc");

                    b.Property<string>("Tomtat");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("TTTN_Travel.Models.Tour", b =>
                {
                    b.Property<int>("Idtour")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDTOUR")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Danhgia")
                        .HasColumnName("DANHGIA");

                    b.Property<decimal?>("Gia")
                        .HasColumnName("GIA")
                        .HasColumnType("money");

                    b.Property<string>("Image")
                        .HasColumnName("IMAGE")
                        .HasMaxLength(50);

                    b.Property<string>("Lichtrinh")
                        .HasColumnName("LICHTRINH");

                    b.Property<string>("Mota")
                        .HasColumnName("MOTA");

                    b.Property<DateTime?>("Ngaybd")
                        .HasColumnName("NGAYBD")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Ngaykt")
                        .HasColumnName("NGAYKT")
                        .HasColumnType("datetime");

                    b.Property<string>("Quocgia")
                        .HasColumnName("QUOCGIA")
                        .HasMaxLength(50);

                    b.Property<string>("Tentuor")
                        .HasColumnName("TENTUOR")
                        .HasMaxLength(150);

                    b.Property<bool?>("Trongnuoc")
                        .HasColumnName("TRONGNUOC");

                    b.HasKey("Idtour");

                    b.ToTable("TOUR");
                });
#pragma warning restore 612, 618
        }
    }
}
